// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.VueJS.Templates.Command
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.TypeScript.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Services.CQRS.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Command\CommandTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class CommandTemplate : TypeScriptTemplateBase<Intent.Modelers.Services.CQRS.Api.CommandModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nexport interface ");
            
            #line 12 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Command\CommandTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 13 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Command\CommandTemplate.tt"
  foreach (var property in Model.Properties) { 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 14 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Command\CommandTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 14 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Command\CommandTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.TypeReference.IsNullable ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 14 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Command\CommandTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypeName(property.TypeReference)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 15 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Command\CommandTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
