// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.Documentation.Templates.Application.IntegrationEventHandler
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Services.EventInteractions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Application\IntegrationEventHandler\IntegrationEventHandlerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class IntegrationEventHandlerTemplate : IntentTemplateBase<Intent.Modelers.Services.EventInteractions.IntegrationEventHandlerModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n## ");
            
            #line 10 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Application\IntegrationEventHandler\IntegrationEventHandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 11 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Application\IntegrationEventHandler\IntegrationEventHandlerTemplate.tt"
 if (!string.IsNullOrWhiteSpace(Model.Comment)) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 13 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Application\IntegrationEventHandler\IntegrationEventHandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 14 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Application\IntegrationEventHandler\IntegrationEventHandlerTemplate.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
