// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.Documentation.Templates.Domain.DomainService
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Domain.Services.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class DomainServiceTemplate : IntentTemplateBase<Intent.Modelers.Domain.Services.Api.DomainServiceModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n## ");
            
            #line 10 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 11 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
 if (!string.IsNullOrWhiteSpace(Model.Comment)) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 13 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 14 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n### Operations\r\n");
            
            #line 17 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
 foreach (var operation in Model.Operations) {
   var sig = string.Join(", ", operation.Parameters.Select(p => $"{GetTypeName(p.TypeReference)} {p.Name}"));

            
            #line default
            #line hidden
            this.Write("\r\n#### ");
            
            #line 21 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 21 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sig));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 22 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
 if (!string.IsNullOrWhiteSpace(operation.Comment)) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 24 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 25 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("##### Parameters\r\n\r\n| Name | Type | Description |\r\n|------|------|-------------|\r" +
                    "\n");
            
            #line 30 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
 foreach (var parameter in operation.Parameters) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 31 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 31 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(parameter.TypeReference)));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 31 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrWhiteSpace(parameter.Comment) ? "" : parameter.Comment));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 32 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 34 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 35 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\DomainService\DomainServiceTemplate.tt"

string GetTypeName(ITypeReference tr)
{
    var name = tr.Element.Name;
    if (tr.IsCollection) name += " []";
    return name;
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
