// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.GitHubIssues.Templates.Domain.DomainEvent
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Domain.Events.Api;
    using Aryzac.GitHubIssues.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class DomainEventTemplate : IntentTemplateBase<Intent.Modelers.Domain.Events.Api.DomainEventModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("---\r\nid: ");
            
            #line 11 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Id));
            
            #line default
            #line hidden
            this.Write("\r\ntitle: \"task(domain event): Add ");
            
            #line 12 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("DomainEvent\"\r\ntype: task\r\n");
            
            #line 14 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
 if (Model.HasGitHubIssueClosed()) { 
            
            #line default
            #line hidden
            this.Write("closed: true\r\n");
            
            #line 16 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("closed: false\r\n");
            
            #line 18 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("---\r\n");
            
            #line 20 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
 if (Model.HasBusinessRequirement()) { 
            
            #line default
            #line hidden
            this.Write("\r\n### Business Goal\r\n\r\n");
            
            #line 24 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.GetBusinessRequirement().Summary()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 25 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
 if (!string.IsNullOrWhiteSpace(Model.Comment)) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 27 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 28 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("\r\n### Scope & Notes\r\n\r\n| Property | Type | Nullable | Description |\r\n|-----------" +
                    "|------|----------|-------------|\r\n");
            
            #line 34 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
 foreach (var property in Model.Properties) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 35 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 35 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.TypeReference.Element.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 35 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.TypeReference.IsCollection ? "[]" : ""));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 35 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.TypeReference.IsNullable ? "Yes" : "No"));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 35 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrWhiteSpace(property.Comment) ? "" : property.Comment));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 36 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
### Checklist

Estimated Effort
Estimated Days: 0.25

| Task                            | Target Hours      |
|---------------------------------|-------------------|
| Define event payload            | 0.25h             |
| Raise event in aggregate        | 0.25h             |
| Implement notification handler  | 0.5h              |
| (Opt) Integration event mapping | 0.5h              |
| Documentation updates           | 0.25h             |
| Buffer                          | 0.25h             |
| Total Target Hours              | 2.0h (≈ 0.25 day) |

Acceptance Checklist
- [ ] ");
            
            #line 54 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("DomainEvent class inherits DomainEvent and is immutable\r\n- [ ] Aggregate appends " +
                    "event after successful state mutation\r\n- [ ] Notification handler (");
            
            #line 56 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\DomainEvent\DomainEventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(@"DomainEventHandler) implemented
- [ ] (Optional) Integration event publish or rationale recorded
- [ ] Validation strategy for aggregate emission/handler recorded (tests or manual)
- [ ] Documentation updated (this recipe referenced)
- [ ] Effort variance >20% captured in issue comments");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
