<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<None Update="Templates\Domain\Domain\DomainTemplate.tt">
			<Generator>TextTemplatingFilePreprocessor</Generator>
			<LastGenOutput>DomainTemplate.cs</LastGenOutput>
			
		</None>
    <None Update="Templates\Domain\DomainEvent\DomainEventTemplate.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>DomainEventTemplate.cs</LastGenOutput>
    </None>
    <None Update="Templates\Application\IntegrationEvent\IntegrationEventTemplate.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>IntegrationEventTemplate.cs</LastGenOutput>
    </None>
    <None Update="Templates\Application\Command\CommandTemplate.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>CommandTemplate.cs</LastGenOutput>
    </None>
    <None Update="Templates\Application\Query\QueryTemplate.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>QueryTemplate.cs</LastGenOutput>
    </None>
    <None Update="Templates\Application\HttpEndpointCommand\HttpEndpointCommandTemplate.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>HttpEndpointCommandTemplate.cs</LastGenOutput>
    </None>
    <None Update="Templates\Application\HttpEndpointQuery\HttpEndpointQueryTemplate.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>HttpEndpointQueryTemplate.cs</LastGenOutput>
    </None>
    <None Update="Templates\Api\HttpEndpointCommand\HttpEndpointCommandTemplate.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>HttpEndpointCommandTemplate.cs</LastGenOutput>
    </None>
    <None Update="Templates\Api\HttpEndpointQuery\HttpEndpointQueryTemplate.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>HttpEndpointQueryTemplate.cs</LastGenOutput>
    </None>
    <None Update="Templates\Domain\DomainDto\DomainDtoTemplate.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>DomainDtoTemplate.cs</LastGenOutput>
    </None>
    <None Update="Templates\Domain\DomainValueObject\DomainValueObjectTemplate.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>DomainValueObjectTemplate.cs</LastGenOutput>
    </None>
    <None Update="Templates\Api\HttpEndpointDto\HttpEndpointDtoTemplate.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>HttpEndpointDtoTemplate.cs</LastGenOutput>
    </None>
    <None Update="Templates\Application\IntegrationEventDto\IntegrationEventDtoTemplate.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>IntegrationEventDtoTemplate.cs</LastGenOutput>
    </None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Intent.Modelers.Domain.Services" Version="1.3.0" />
	  <PackageReference Include="Intent.Modules.Common" Version="3.8.0" />
	  <PackageReference Include="Intent.Modules.Modelers.Domain" Version="3.12.8" />
	  <PackageReference Include="Intent.Modules.Modelers.Domain.Events" Version="4.4.4" />
	  <PackageReference Include="Intent.Modules.Modelers.Domain.ValueObjects" Version="3.6.2" />
	  <PackageReference Include="Intent.Modules.Modelers.Eventing" Version="6.0.2" />
	  <PackageReference Include="Intent.Modules.Modelers.Services" Version="4.0.5" />
	  <PackageReference Include="Intent.Modules.Modelers.Services.CQRS" Version="6.0.4" />
	  <PackageReference Include="Intent.Modules.Modelers.Services.EventInteractions" Version="2.0.3" />
	  <PackageReference Include="Intent.Packager" Version="3.6.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	  <PackageReference Include="Intent.RoslynWeaver.Attributes" Version="3.0.0" />
	  <PackageReference Include="Intent.SoftwareFactory.SDK" Version="3.7.0" />
	</ItemGroup>

	<ItemGroup>
		<Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

  <ItemGroup>
    <Compile Update="Templates\Api\HttpEndpointCommand\HttpEndpointCommandTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HttpEndpointCommandTemplate.tt</DependentUpon>
    </Compile>
    <Compile Update="Templates\Api\HttpEndpointDto\HttpEndpointDtoTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HttpEndpointDtoTemplate.tt</DependentUpon>
    </Compile>
    <Compile Update="Templates\Api\HttpEndpointQuery\HttpEndpointQueryTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HttpEndpointQueryTemplate.tt</DependentUpon>
    </Compile>
    <Compile Update="Templates\Application\Command\CommandTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CommandTemplate.tt</DependentUpon>
    </Compile>
    <Compile Update="Templates\Application\HttpEndpointCommand\HttpEndpointCommandTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HttpEndpointCommandTemplate.tt</DependentUpon>
    </Compile>
    <Compile Update="Templates\Application\HttpEndpointQuery\HttpEndpointQueryTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HttpEndpointQueryTemplate.tt</DependentUpon>
    </Compile>
    <Compile Update="Templates\Application\IntegrationEventDto\IntegrationEventDtoTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>IntegrationEventDtoTemplate.tt</DependentUpon>
    </Compile>
    <Compile Update="Templates\Application\IntegrationEvent\IntegrationEventTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>IntegrationEventTemplate.tt</DependentUpon>
    </Compile>
    <Compile Update="Templates\Application\Query\QueryTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>QueryTemplate.tt</DependentUpon>
    </Compile>
    <Compile Update="Templates\Domain\DomainDto\DomainDtoTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DomainDtoTemplate.tt</DependentUpon>
    </Compile>
    <Compile Update="Templates\Domain\DomainEvent\DomainEventTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DomainEventTemplate.tt</DependentUpon>
    </Compile>
    <Compile Update="Templates\Domain\DomainValueObject\DomainValueObjectTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DomainValueObjectTemplate.tt</DependentUpon>
    </Compile>
    <Compile Update="Templates\Domain\Domain\DomainTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DomainTemplate.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>