// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.GitHubIssues.Templates.Application.Query
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Services.CQRS.Api;
    using Aryzac.GitHubIssues.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class QueryTemplate : IntentTemplateBase<Intent.Modelers.Services.CQRS.Api.QueryModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("---\r\nid: ");
            
            #line 11 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Id));
            
            #line default
            #line hidden
            this.Write("\r\ntitle: \"task(query): Add ");
            
            #line 12 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(" query handler\"\r\ntype: task\r\n");
            
            #line 14 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
 if (Model.HasGitHubIssueClosed()) { 
            
            #line default
            #line hidden
            this.Write("closed: true\r\n");
            
            #line 16 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("closed: false\r\n");
            
            #line 18 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("---\r\n");
            
            #line 20 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
 if (Model.HasBusinessRequirement()) { 
            
            #line default
            #line hidden
            this.Write("\r\n### Business Goal\r\n\r\n");
            
            #line 24 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.GetBusinessRequirement().Summary()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 25 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
 if (!string.IsNullOrWhiteSpace(Model.Comment)) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 27 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 28 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("\r\n### Scope & Notes\r\n\r\n| Property | Type | Nullable | Description |\r\n|-----------" +
                    "|------|----------|-------------|\r\n");
            
            #line 34 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
 foreach (var property in Model.Properties) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 35 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 35 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.TypeReference.Element.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 35 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.TypeReference.IsCollection ? "[]" : ""));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 35 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.TypeReference.IsNullable ? "Yes" : "No"));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 35 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrWhiteSpace(property.Comment) ? "" : property.Comment));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 36 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
Estimated Effort
Estimated Days: 0.5

| Task                                          | Target Hours      |
|-----------------------------------------------|-------------------|
| Define query + DTO                            | 0.5h              |
| Add validator (if required)                   | 0.25h             |
| Implement handler (projection + filters)      | 0.75h             |
| Tests (happy, not found, pagination/ordering) | 1.0h              |
| Documentation updates                         | 0.25h             |
| Buffer                                        | 0.25h             |
| Total Target Hours                            | 2.75h (≈ 0.5 day) |

Acceptance Checklist
- [ ] Query implements IRequest<");
            
            #line 52 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Application\Query\QueryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(@"> (+ IQuery if applicable)
- [ ] DTO defined and returned (no domain entity leakage)
- [ ] Handler uses repository IQueryable + ProjectTo + AsNoTracking
- [ ] NotFoundException thrown when entity missing
- [ ] Pagination/ordering/filters handled or N/A documented
- [ ] Tests cover happy path, not found, filter/pagination cases
- [ ] Documentation updated (this recipe referenced)
- [ ] Effort variance >20% captured in issue comments
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
