// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.Documentation.Templates.Domain.Domain
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Domain.Api;
    using Intent.Modelers.Domain.Events.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class DomainTemplate : IntentTemplateBase<Intent.Modelers.Domain.Api.ClassModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n---\r\ntitle: ");
            
            #line 12 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EscapeYaml(Model.Name.ToSentenceCase())));
            
            #line default
            #line hidden
            this.Write("\r\ndescription: ");
            
            #line 13 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EscapeYaml(SingleLine(Model.Comment))));
            
            #line default
            #line hidden
            this.Write("\r\n---\r\n");
            
            #line 15 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (!string.IsNullOrWhiteSpace(Model.Comment)) { 
            
            #line default
            #line hidden
            
            #line 16 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 18 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 19 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (Model.Attributes.Any()) { 
            
            #line default
            #line hidden
            this.Write("## Attributes\r\n\r\n::field-group\r\n");
            
            #line 23 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var attribute in Model.Attributes) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 24 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FormatFieldTag(
        name: attribute.Name,
        type: GetTypeName(attribute.TypeReference),
        required: !attribute.TypeReference.IsNullable,
        defaultValue: attribute.Value?.ToString()
      )));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 30 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
   if (!string.IsNullOrWhiteSpace(attribute.Comment)) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 31 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 32 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
   } 
            
            #line default
            #line hidden
            this.Write("  ::\r\n");
            
            #line 34 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("::\r\n");
            
            #line 36 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n## Constructors\r\n");
            
            #line 39 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var constructor in Model.Constructors) {
   var sig = string.Join(", ", constructor.Parameters.Select(p => $"{GetTypeName(p.TypeReference)} {p.Name}"));

            
            #line default
            #line hidden
            this.Write("\r\n### ");
            
            #line 43 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 44 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (!string.IsNullOrWhiteSpace(constructor.Comment)) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 46 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(constructor.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 48 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 50 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (constructor.Parameters.Any()) { 
            
            #line default
            #line hidden
            this.Write("#### Parameters\r\n\r\n::field-group\r\n");
            
            #line 54 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var parameter in constructor.Parameters) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 55 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FormatFieldTag(
        name: parameter.Name,
        type: GetTypeName(parameter.TypeReference),
        required: !parameter.TypeReference.IsNullable,
        defaultValue: null
      )));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 61 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
   if (!string.IsNullOrWhiteSpace(parameter.Comment)) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 62 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 63 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
   } 
            
            #line default
            #line hidden
            this.Write("  ::\r\n");
            
            #line 65 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("::\r\n");
            
            #line 67 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 69 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 var ctorEvents = constructor.PublishedDomainEvents().ToList();
   if (ctorEvents.Any()) { 
            
            #line default
            #line hidden
            this.Write("#### Published Domain Events\r\n\r\n| Domain Event | Description |\r\n|--------------|-" +
                    "------------|\r\n");
            
            #line 75 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
   foreach (var de in ctorEvents) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 76 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(de.Element.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 76 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrWhiteSpace(de.Element.Comment) ? "" : de.Element.Comment));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 77 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
   } 
            
            #line default
            #line hidden
            
            #line 78 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 79 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 81 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (Model.Operations.Any()) { 
            
            #line default
            #line hidden
            this.Write("## Operations\r\n");
            
            #line 83 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var operation in Model.Operations) {
   var sig = string.Join(", ", operation.Parameters.Select(p => $"{GetTypeName(p.TypeReference)} {p.Name}"));

            
            #line default
            #line hidden
            this.Write("\r\n### ");
            
            #line 87 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 88 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (!string.IsNullOrWhiteSpace(operation.Comment)) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 90 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 91 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 93 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (operation.Parameters.Any()) { 
            
            #line default
            #line hidden
            this.Write("#### Parameters\r\n\r\n::field-group\r\n");
            
            #line 97 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var parameter in operation.Parameters) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 98 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FormatFieldTag(
        name: parameter.Name,
        type: GetTypeName(parameter.TypeReference),
        required: !parameter.TypeReference.IsNullable,
        defaultValue: null
      )));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 104 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
   if (!string.IsNullOrWhiteSpace(parameter.Comment)) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 105 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 106 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
   } 
            
            #line default
            #line hidden
            this.Write("  ::\r\n");
            
            #line 108 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("::\r\n");
            
            #line 110 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 112 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 var opEvents = operation.PublishedDomainEvents().ToList();
   if (opEvents.Any()) { 
            
            #line default
            #line hidden
            this.Write("#### Published Domain Events\r\n\r\n| Domain Event | Description |\r\n|--------------|-" +
                    "------------|\r\n");
            
            #line 118 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
   foreach (var de in opEvents) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 119 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(de.Element.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 119 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrWhiteSpace(de.Element.Comment) ? "" : de.Element.Comment));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 120 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
   } 
            
            #line default
            #line hidden
            
            #line 121 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 122 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 123 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 125 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (Model.AssociatedToClasses().Any()) { 
            
            #line default
            #line hidden
            this.Write("## Outbound Associations\r\n\r\n| Associated Class | Multiplicity |\r\n|---------------" +
                    "---|-------------|\r\n");
            
            #line 130 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var associatedClass in Model.AssociatedToClasses()) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 131 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associatedClass.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 131 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associatedClass.Multiplicity.ToString()));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 132 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 133 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 135 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (Model.AssociatedFromClasses().Any()) { 
            
            #line default
            #line hidden
            this.Write("## Inbound Associations\r\n\r\n| Associated Class | Multiplicity |\r\n|----------------" +
                    "--|-------------|\r\n");
            
            #line 140 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var associatedClass in Model.AssociatedFromClasses()) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 141 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associatedClass.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 141 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associatedClass.Multiplicity.ToString()));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 142 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 143 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 145 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"

string GetTypeName(ITypeReference tr)
{
    var name = tr.Element.Name;
    if (tr.IsCollection) name += " []";
    return name;
}

string FormatFieldTag(string name, string type, bool required, string defaultValue)
{
    var parts = new List<string>
    {
        $"name=\"{EscapeAttr(name)}\"",
        $"type=\"{EscapeAttr(type)}\""
    };

    if (!string.IsNullOrWhiteSpace(defaultValue))
    {
        parts.Add($"defaultValue=\"{EscapeAttr(defaultValue)}\"");
    }

    if (required)
    {
        parts.Add("required");
    }

    return $"::field{{{string.Join(" ", parts)}}}";
}

string EscapeAttr(string value)
{
    if (value == null) return string.Empty;
    return value.Replace("\"", "&quot;");
}

string EscapeYaml(string value)
{
    if (string.IsNullOrWhiteSpace(value)) return "\"\"";

    // YAML-safe double-quoted scalar. Also keep it single-line.
    var v = SingleLine(value)
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");
    return $"\"{v}\"";
}

string SingleLine(string value)
{
    if (string.IsNullOrWhiteSpace(value)) return string.Empty;
    return value
        .Replace("\r\n", " ")
        .Replace("\n", " ")
        .Replace("\r", " ")
        .Trim();
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
