// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.Documentation.Templates.Domain.Domain
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Domain.Api;
    using Intent.Modelers.Domain.Events.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class DomainTemplate : IntentTemplateBase<Intent.Modelers.Domain.Api.ClassModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n## ");
            
            #line 11 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 12 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (!string.IsNullOrWhiteSpace(Model.Comment)) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 14 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 15 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n| Attribute | Type | Nullable | Default | Description |\r\n|-----------|------|--" +
                    "--------|---------|-------------|\r\n");
            
            #line 19 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var attribute in Model.Attributes) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 20 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 20 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(attribute.TypeReference)));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 20 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.TypeReference.IsNullable ? "Yes" : "No"));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 20 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Value));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 20 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrWhiteSpace(attribute.Comment) ? "" : attribute.Comment));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 21 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n### Constructors\r\n");
            
            #line 24 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var constructor in Model.Constructors) {
   var sig = string.Join(", ", constructor.Parameters.Select(p => $"{GetTypeName(p.TypeReference)} {p.Name}"));

            
            #line default
            #line hidden
            this.Write("\r\n#### ");
            
            #line 28 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 28 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sig));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 29 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (!string.IsNullOrWhiteSpace(constructor.Comment)) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 31 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(constructor.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 33 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 34 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (constructor.Parameters.Any()) { 
            
            #line default
            #line hidden
            this.Write("##### Parameters\r\n\r\n| Name | Type | Description |\r\n|------|------|-------------|\r" +
                    "\n");
            
            #line 39 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var parameter in constructor.Parameters) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 40 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 40 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(parameter.TypeReference)));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 40 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrWhiteSpace(parameter.Comment) ? "" : parameter.Comment));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 41 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 43 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 var events = constructor.PublishedDomainEvents().ToList();
   if (events.Any()) { 
            
            #line default
            #line hidden
            this.Write("##### Published Domain Events\r\n\r\n| Domain Event | Description |\r\n|--------------|" +
                    "-------------|\r\n");
            
            #line 49 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
   foreach (var de in events) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 50 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(de.Element.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 50 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrWhiteSpace(de.Element.Comment) ? "" : de.Element.Comment));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 51 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
   } 
            
            #line default
            #line hidden
            
            #line 52 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 54 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (Model.Operations.Any()) { 
            
            #line default
            #line hidden
            this.Write("### Operations\r\n");
            
            #line 56 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var operation in Model.Operations) {
   var sig = string.Join(", ", operation.Parameters.Select(p => $"{GetTypeName(p.TypeReference)} {p.Name}"));

            
            #line default
            #line hidden
            this.Write("\r\n#### ");
            
            #line 60 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 60 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sig));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 61 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (!string.IsNullOrWhiteSpace(operation.Comment)) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 63 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 64 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 65 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (operation.Parameters.Any()) { 
            
            #line default
            #line hidden
            this.Write("##### Parameters\r\n\r\n| Name | Type | Description |\r\n|------|------|-------------|\r" +
                    "\n");
            
            #line 70 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var parameter in operation.Parameters) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 71 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 71 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(parameter.TypeReference)));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 71 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrWhiteSpace(parameter.Comment) ? "" : parameter.Comment));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 72 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 74 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 var events = operation.PublishedDomainEvents().ToList();
   if (events.Any()) { 
            
            #line default
            #line hidden
            this.Write("##### Published Domain Events\r\n\r\n| Domain Event | Description |\r\n|--------------|" +
                    "-------------|\r\n");
            
            #line 80 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
   foreach (var de in events) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 81 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(de.Element.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 81 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrWhiteSpace(de.Element.Comment) ? "" : de.Element.Comment));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 82 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
   } 
            
            #line default
            #line hidden
            
            #line 83 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } } } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 85 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (Model.AssociatedToClasses().Any()) { 
            
            #line default
            #line hidden
            this.Write("### Outbound Associations\r\n\r\n| Associated Class | Multiplicity |\r\n|--------------" +
                    "----|------|\r\n");
            
            #line 90 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var associatedClass in Model.AssociatedToClasses()) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 91 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associatedClass.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 91 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associatedClass.Multiplicity.ToString()));
            
            #line default
            #line hidden
            this.Write(" |\r\n\r\n");
            
            #line 93 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } } 
            
            #line default
            #line hidden
            
            #line 94 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 if (Model.AssociatedFromClasses().Any()) { 
            
            #line default
            #line hidden
            this.Write("### Inbound Associations\r\n\r\n| Associated Class | Multiplicity |\r\n|---------------" +
                    "---|------|\r\n");
            
            #line 99 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var associatedClass in Model.AssociatedFromClasses()) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 100 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associatedClass.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 100 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associatedClass.Multiplicity.ToString()));
            
            #line default
            #line hidden
            this.Write(" |\r\n\r\n");
            
            #line 102 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"
 } } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 103 "E:\aryzac-io\intent-modules\src\Aryzac.Documentation\Templates\Domain\Domain\DomainTemplate.tt"

string GetTypeName(ITypeReference tr)
{
    var name = tr.Element.Name;
    if (tr.IsCollection) name += " []";
    return name;
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
