// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.VueJS.Templates.Composable
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Text.RegularExpressions;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.TypeScript.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Aryzac.VueJS.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class ComposableTemplate : TypeScriptTemplateBase<Aryzac.VueJS.Api.ComposableModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 13 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

    var services = GetServices().ToList();

    var imports = new List<(string Name, string Path)>();

    foreach (var service in services)
    {
        var scopes = GetScopes(service);
        var route = GetRoute(service);
        var isGet = string.Equals(route.Method, "GET", StringComparison.OrdinalIgnoreCase);
        var isVersioned = route.Versioned;

        var routeRequestType = GetRouteRequestType(service);
        var hasRequest = routeRequestType != null && routeRequestType.ChildElements.Any();

        var requestTypeName = routeRequestType?.Name ?? "UNKNOWN";
        
        var routeResponseType = GetRouteResponseType(service);
        var hasResponse = routeResponseType != null && routeResponseType.ChildElements.Any();

        var responseTypeName = routeResponseType?.Name ?? "UNKNOWN";

        if (hasRequest)
        {

            
            #line default
            #line hidden
            
            #line 38 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AddImport(routeRequestType)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 39 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

        }

        if (hasResponse)
        {

            
            #line default
            #line hidden
            
            #line 45 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AddImport(routeResponseType)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 46 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("export function use");
            
            #line 50 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("() {\r\n\r\n");
            
            #line 52 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

    foreach (var service in services)
    {
        var scopes = GetScopes(service);
        var route = GetRoute(service);
        var isGet = string.Equals(route.Method, "GET", StringComparison.OrdinalIgnoreCase);
        var isVersioned = route.Versioned;

        var routeRequestType = GetRouteRequestType(service);
        var hasRequest = routeRequestType != null && routeRequestType.ChildElements.Any();

        var requestTypeName = routeRequestType?.Name ?? "UNKNOWN";
        
        var routeResponseType = GetRouteResponseType(service);
        var hasResponse = routeResponseType != null && routeResponseType.ChildElements.Any();

        var responseTypeName = routeResponseType?.Name ?? "UNKNOWN";

        // Split request props into path vs query based on Express-style :placeholders in the route
        var placeholderMatches = Regex.Matches(route.Path, ":([^/]+)")
            .Cast<Match>()
            .ToList();

        var placeholderMap = placeholderMatches
            .GroupBy(m => m.Groups[1].Value, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(g => g.Key, g => g.First().Groups[1].Value, StringComparer.OrdinalIgnoreCase);

        var pathProps = hasRequest
            ? routeRequestType.ChildElements
                .Where(p => placeholderMap.ContainsKey(p.Name))
                .ToList()
            : new List<Intent.Metadata.Models.IElement>();

        var queryProps = hasRequest
            ? routeRequestType.ChildElements
                .Where(p => !placeholderMap.ContainsKey(p.Name))
                .ToList()
            : new List<Intent.Metadata.Models.IElement>();

        // Signature
        var paramParts = new List<string>();

        if (isVersioned)
        {
            // version is not part of the request DTO
            paramParts.Add("version: string");
        }

        if (hasRequest)
        {
            if (isGet)
            {
                // GET: keep single request DTO
                paramParts.Add($"request: {requestTypeName}");
            }
            else
            {
                // non-GET: lift only path props; everything else stays in body
                foreach (var prop in pathProps)
                {
                    var tsName = prop.Name.ToCamelCase();
                    var tsType = GetTypeName(prop.TypeReference);
                    paramParts.Add($"{tsName}: {tsType}");
                }

                // full body still passed
                paramParts.Add($"body: {requestTypeName}");
            }
        }

        paramParts.Add("options?: any");

        var paramSignature = string.Join(", ", paramParts);

            
            #line default
            #line hidden
            this.Write("    const ");
            
            #line 126 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" = async (");
            
            #line 126 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(paramSignature));
            
            #line default
            #line hidden
            this.Write(") => {\r\n");
            
            #line 127 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

        if (hasResponse)
        {

            
            #line default
            #line hidden
            this.Write("        const result = await useApi<");
            
            #line 131 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(responseTypeName));
            
            #line default
            #line hidden
            this.Write(">(\r\n            \'");
            
            #line 132 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(route.Path));
            
            #line default
            #line hidden
            this.Write("\',\r\n            {\r\n                ...(options || {}),\r\n                method: \'" +
                    "");
            
            #line 135 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(route.Method));
            
            #line default
            #line hidden
            this.Write("\',\r\n");
            
            #line 136 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

            if (isGet)
            {
                var hasPathProps = hasRequest && pathProps.Any();
                var needsParams = isVersioned || hasPathProps;

                if (needsParams)
                {

            
            #line default
            #line hidden
            this.Write("                params: {\r\n");
            
            #line 146 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                    if (isVersioned)
                    {

            
            #line default
            #line hidden
            this.Write("                    version: version");
            
            #line 150 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(hasPathProps ? "," : ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 151 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                    }
                    if (hasPathProps)
                    {
                        for (var i = 0; i < pathProps.Count; i++)
                        {
                            var prop = pathProps[i];
                            var tsName = prop.Name.ToCamelCase();
                            var placeholderName = placeholderMap[prop.Name];

            
            #line default
            #line hidden
            this.Write("                    ");
            
            #line 161 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(placeholderName));
            
            #line default
            #line hidden
            this.Write(": request.");
            
            #line 161 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tsName));
            
            #line default
            #line hidden
            
            #line 161 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i < pathProps.Count - 1 ? "," : ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 162 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                        }
                    }

            
            #line default
            #line hidden
            this.Write("                },\r\n");
            
            #line 167 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                }

                if (hasRequest && queryProps.Any())
                {

            
            #line default
            #line hidden
            this.Write("                query: {\r\n");
            
            #line 174 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                    for (var i = 0; i < queryProps.Count; i++)
                    {
                        var prop = queryProps[i];
                        var tsName = prop.Name.ToCamelCase();

            
            #line default
            #line hidden
            this.Write("                    ");
            
            #line 180 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tsName));
            
            #line default
            #line hidden
            this.Write(": request.");
            
            #line 180 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tsName));
            
            #line default
            #line hidden
            
            #line 180 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i < queryProps.Count - 1 ? "," : ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 181 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                    }

            
            #line default
            #line hidden
            this.Write("                },\r\n");
            
            #line 185 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                }
            }
            else
            {
                // non-GET
                if (hasRequest)
                {

            
            #line default
            #line hidden
            this.Write("                body,\r\n");
            
            #line 195 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                }

                var nonGetHasPathProps = hasRequest && pathProps.Any();
                var nonGetNeedsParams = isVersioned || nonGetHasPathProps;

                if (nonGetNeedsParams)
                {

            
            #line default
            #line hidden
            this.Write("                params: {\r\n");
            
            #line 205 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                    if (isVersioned)
                    {

            
            #line default
            #line hidden
            this.Write("                    version: version");
            
            #line 209 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nonGetHasPathProps ? "," : ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 210 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                    }
                    if (nonGetHasPathProps)
                    {
                        for (var i = 0; i < pathProps.Count; i++)
                        {
                            var prop = pathProps[i];
                            var tsName = prop.Name.ToCamelCase();
                            var placeholderName = placeholderMap[prop.Name];

            
            #line default
            #line hidden
            this.Write("                    ");
            
            #line 220 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(placeholderName));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 220 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tsName));
            
            #line default
            #line hidden
            
            #line 220 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i < pathProps.Count - 1 ? "," : ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 221 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                        }
                    }

            
            #line default
            #line hidden
            this.Write("                },\r\n");
            
            #line 226 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                }
                // no query for non-GET; non-path properties stay in body
            }

            
            #line default
            #line hidden
            this.Write("                scopes: [");
            
            #line 231 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(scopes));
            
            #line default
            #line hidden
            this.Write("],\r\n            }\r\n        );\r\n        return result;\r\n");
            
            #line 235 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("        await useApi(\r\n            \'");
            
            #line 241 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(route.Path));
            
            #line default
            #line hidden
            this.Write("\',\r\n            {\r\n                ...(options || {}),\r\n                method: \'" +
                    "");
            
            #line 244 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(route.Method));
            
            #line default
            #line hidden
            this.Write("\',\r\n");
            
            #line 245 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

            if (isGet)
            {
                var hasPathProps = hasRequest && pathProps.Any();
                var needsParams = isVersioned || hasPathProps;

                if (needsParams)
                {

            
            #line default
            #line hidden
            this.Write("                params: {\r\n");
            
            #line 255 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                    if (isVersioned)
                    {

            
            #line default
            #line hidden
            this.Write("                    version: version");
            
            #line 259 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(hasPathProps ? "," : ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 260 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                    }
                    if (hasPathProps)
                    {
                        for (var i = 0; i < pathProps.Count; i++)
                        {
                            var prop = pathProps[i];
                            var tsName = prop.Name.ToCamelCase();
                            var placeholderName = placeholderMap[prop.Name];

            
            #line default
            #line hidden
            this.Write("                    ");
            
            #line 270 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(placeholderName));
            
            #line default
            #line hidden
            this.Write(": request.");
            
            #line 270 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tsName));
            
            #line default
            #line hidden
            
            #line 270 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i < pathProps.Count - 1 ? "," : ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 271 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                        }
                    }

            
            #line default
            #line hidden
            this.Write("                },\r\n");
            
            #line 276 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                }

                if (hasRequest && queryProps.Any())
                {

            
            #line default
            #line hidden
            this.Write("                query: {\r\n");
            
            #line 283 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                    for (var i = 0; i < queryProps.Count; i++)
                    {
                        var prop = queryProps[i];
                        var tsName = prop.Name.ToCamelCase();

            
            #line default
            #line hidden
            this.Write("                    ");
            
            #line 289 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tsName));
            
            #line default
            #line hidden
            this.Write(": request.");
            
            #line 289 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tsName));
            
            #line default
            #line hidden
            
            #line 289 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i < queryProps.Count - 1 ? "," : ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 290 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                    }

            
            #line default
            #line hidden
            this.Write("                },\r\n");
            
            #line 294 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                }
            }
            else
            {
                // non-GET
                if (hasRequest)
                {

            
            #line default
            #line hidden
            this.Write("                body,\r\n");
            
            #line 304 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                }

                var nonGetHasPathProps = hasRequest && pathProps.Any();
                var nonGetNeedsParams = isVersioned || nonGetHasPathProps;

                if (nonGetNeedsParams)
                {

            
            #line default
            #line hidden
            this.Write("                params: {\r\n");
            
            #line 314 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                    if (isVersioned)
                    {

            
            #line default
            #line hidden
            this.Write("                    version: version");
            
            #line 318 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nonGetHasPathProps ? "," : ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 319 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                    }
                    if (nonGetHasPathProps)
                    {
                        for (var i = 0; i < pathProps.Count; i++)
                        {
                            var prop = pathProps[i];
                            var tsName = prop.Name.ToCamelCase();
                            var placeholderName = placeholderMap[prop.Name];

            
            #line default
            #line hidden
            this.Write("                    ");
            
            #line 329 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(placeholderName));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 329 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tsName));
            
            #line default
            #line hidden
            
            #line 329 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i < pathProps.Count - 1 ? "," : ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 330 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                        }
                    }

            
            #line default
            #line hidden
            this.Write("                },\r\n");
            
            #line 335 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

                }
                // no query for non-GET; non-path properties stay in body
            }

            
            #line default
            #line hidden
            this.Write("                scopes: [");
            
            #line 340 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(scopes));
            
            #line default
            #line hidden
            this.Write("],\r\n            }\r\n        );\r\n");
            
            #line 343 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("    }\r\n");
            
            #line 347 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n    return {\r\n");
            
            #line 352 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

    foreach (var service in services)
    {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 356 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 357 "E:\aryzac-io\intent-modules\src\Aryzac.VueJS\Templates\Composable\ComposableTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
