// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aryzac.GitHubIssues.Templates.Domain.Domain
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Domain.Api;
    using Intent.Modelers.Domain.Events.Api;
    using Aryzac.GitHubIssues.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class DomainTemplate : IntentTemplateBase<Intent.Modelers.Domain.Api.ClassModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("---\r\nid: ");
            
            #line 12 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Id));
            
            #line default
            #line hidden
            this.Write("\r\ntitle: \"task(domain): Introduce ");
            
            #line 13 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(" domain entity\"\r\ntype: task\r\n");
            
            #line 15 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 if (Model.HasGitHubIssueClosed()) { 
            
            #line default
            #line hidden
            this.Write("closed: true\r\n");
            
            #line 17 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("closed: false\r\n");
            
            #line 19 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("---\r\n");
            
            #line 21 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 if (Model.HasBusinessRequirement()) { 
            
            #line default
            #line hidden
            this.Write("\r\n### Business Goal\r\n\r\n");
            
            #line 25 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.GetBusinessRequirement().Summary()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 26 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 if (!string.IsNullOrWhiteSpace(Model.Comment)) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 28 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 29 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("\r\n### Scope & Notes\r\n\r\n| Attribute | Type | Nullable | Default | Description |\r\n|" +
                    "-----------|------|----------|---------|-------------|\r\n");
            
            #line 35 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var attribute in Model.Attributes) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 36 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 36 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(attribute.TypeReference)));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 36 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.TypeReference.IsNullable ? "Yes" : "No"));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 36 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Value));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 36 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrWhiteSpace(attribute.Comment) ? "" : attribute.Comment));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 37 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n#### Constructors\r\n");
            
            #line 40 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var constructor in Model.Constructors) {
   var sig = string.Join(", ", constructor.Parameters.Select(p => $"{GetTypeName(p.TypeReference)} {p.Name}"));

            
            #line default
            #line hidden
            this.Write("\r\n##### ");
            
            #line 44 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 44 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sig));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 45 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 if (!string.IsNullOrWhiteSpace(constructor.Comment)) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 47 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(constructor.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 49 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 50 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 if (constructor.Parameters.Any()) { 
            
            #line default
            #line hidden
            this.Write("\r\n###### Parameters\r\n\r\n| Name | Type | Description |\r\n|------|------|------------" +
                    "-|\r\n");
            
            #line 56 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var parameter in constructor.Parameters) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 57 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 57 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(parameter.TypeReference)));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 57 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrWhiteSpace(parameter.Comment) ? "" : parameter.Comment));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 58 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 60 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 var events = constructor.PublishedDomainEvents().ToList();
   if (events.Any()) { 
            
            #line default
            #line hidden
            this.Write("###### Published Domain Events\r\n\r\n| Domain Event | Description |\r\n|--------------" +
                    "|-------------|\r\n");
            
            #line 66 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
   foreach (var de in events) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 67 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(de.Element.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 67 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrWhiteSpace(de.Element.Comment) ? "" : de.Element.Comment));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 68 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
   } 
            
            #line default
            #line hidden
            
            #line 69 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 71 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 if (Model.Operations.Any()) { 
            
            #line default
            #line hidden
            this.Write("#### Operations\r\n");
            
            #line 73 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var operation in Model.Operations) {
   var sig = string.Join(", ", operation.Parameters.Select(p => $"{GetTypeName(p.TypeReference)} {p.Name}"));

            
            #line default
            #line hidden
            this.Write("\r\n##### ");
            
            #line 77 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 77 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sig));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 78 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 if (!string.IsNullOrWhiteSpace(operation.Comment)) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 80 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 81 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 82 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 if (operation.Parameters.Any()) { 
            
            #line default
            #line hidden
            this.Write("\r\n###### Parameters\r\n\r\n| Name | Type | Description |\r\n|------|------|------------" +
                    "-|\r\n");
            
            #line 88 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var parameter in operation.Parameters) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 89 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 89 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(parameter.TypeReference)));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 89 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrWhiteSpace(parameter.Comment) ? "" : parameter.Comment));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 90 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 92 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 var events = operation.PublishedDomainEvents().ToList();
   if (events.Any()) { 
            
            #line default
            #line hidden
            this.Write("###### Published Domain Events\r\n\r\n| Domain Event | Description |\r\n|--------------" +
                    "|-------------|\r\n");
            
            #line 98 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
   foreach (var de in events) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 99 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(de.Element.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 99 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.IsNullOrWhiteSpace(de.Element.Comment) ? "" : de.Element.Comment));
            
            #line default
            #line hidden
            this.Write(" |\r\n");
            
            #line 100 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
   } 
            
            #line default
            #line hidden
            
            #line 101 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 } } } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 103 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 if (Model.AssociatedToClasses().Any()) { 
            
            #line default
            #line hidden
            this.Write("#### Outbound Associations\r\n\r\n| Associated Class | Multiplicity |\r\n|-------------" +
                    "-----|------|\r\n");
            
            #line 108 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var associatedClass in Model.AssociatedToClasses()) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 109 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associatedClass.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 109 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associatedClass.Multiplicity.ToString()));
            
            #line default
            #line hidden
            this.Write(" |\r\n\r\n");
            
            #line 111 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 } } 
            
            #line default
            #line hidden
            
            #line 112 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 if (Model.AssociatedFromClasses().Any()) { 
            
            #line default
            #line hidden
            this.Write("#### Inbound Associations\r\n\r\n| Associated Class | Multiplicity |\r\n|--------------" +
                    "----|------|\r\n");
            
            #line 117 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 foreach (var associatedClass in Model.AssociatedFromClasses()) { 
            
            #line default
            #line hidden
            this.Write("| ");
            
            #line 118 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associatedClass.Name));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 118 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associatedClass.Multiplicity.ToString()));
            
            #line default
            #line hidden
            this.Write(" |\r\n\r\n");
            
            #line 120 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("\r\n### Checklist\r\n\r\nEstimated Effort\r\nEstimated Days: 1\r\n\r\n| Task                 " +
                    "                            | Target Hours   |\r\n|-------------------------------" +
                    "-------------------|----------------|\r\n| Define interface (I");
            
            #line 129 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(@")            | 0.5h           |
| Behavioural partial class (+ constructor events) | 1.0h           |
| State partial class (private setters)            | 0.5h           |
| Domain events (created/other)                    | 0.5h           |
| EF configuration                                 | 0.5h           |
| DbContext registration                           | 0.25h          |
| Repository interface + implementation            | 1.0h           |
| DI registration                                  | 0.25h          |
| Multi-tenant adaptation (opt)                    | 0.5h           |
| Soft delete adaptation (opt)                     | 0.5h           |
| Documentation updates                            | 0.5h           |
| Buffer                                           | 0.5h           |
| Total Target Hours                               | 6.0h (≈ 1 day) |

Acceptance Checklist
- [ ] Interface I");
            
            #line 144 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(" defined\r\n- [ ] Behaviour partial (");
            
            #line 145 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(".cs) implements invariants + raises events\r\n- [ ] State partial (");
            
            #line 146 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(@"State.cs) contains persistence shape only
- [ ] Domain events created or updated as required
- [ ] EF configuration ignores DomainEvents and enforces schema
- [ ] DbContext updated with DbSet + ApplyConfiguration
- [ ] Repository interface + implementation returning abstractions
- [ ] DI registration added
- [ ] Multi-tenant handling N/A or implemented
- [ ] Soft delete handling N/A or implemented
- [ ] Validation approach for behaviour/persistence captured (automated or manual)
- [ ] Documentation updated (this recipe referenced)
- [ ] Effort variance >20% noted

");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 158 "E:\aryzac-io\intent-modules\src\Aryzac.GitHubIssues\Templates\Domain\Domain\DomainTemplate.tt"

string GetTypeName(ITypeReference tr)
{
    var name = tr.Element.Name;
    if (tr.IsCollection) name += " []";
    return name;
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
